apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets
  - feature-store
  - storage/triton-model-repo/pv-pvc.yaml
  - network-policies/triton-netpol.yaml
  - network-policies/mlflow-netpol.yaml
  - network-policies/fastapi-netpol.yaml
  - network-policies/airflow-netpol.yaml
