{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fastapi.fullname" . }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ include "fastapi.name" . }}
  endpoints:
    - path: /metrics
      port: http
      interval: 30s
{{- end }}
